/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Soldier.glb -o src/components/Soldier.jsx -k -K -r public 
*/

import React, { useEffect } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Soldier({
  animation,
  ...props}) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/Soldier.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

     useEffect(() => {
        //  console.log('Rick Loaded Materials:', materials);
        actions[animation]?.reset().fadeIn(0.24).play();
        return () => actions?.[animation]?.fadeOut(0.24);
      }, [animation]);


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh name="Mesh1_Mesh1001" geometry={nodes.Mesh1_Mesh1001.geometry} material={materials['Material.001']} skeleton={nodes.Mesh1_Mesh1001.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/Soldier.glb')
